### ISSUE TITLE
(Libretro) Build failures

### ISSUE THREAD

**Issue by LibretroAdmin** [drhelius/Gearcoleco#68]
Hi there,

there have been build failures for the Libretro core since yesterday.

Here you can see more information which hopefully is helpful:
https://git.libretro.com/libretro/gearcoleco/-/pipelines/313449

**Comment by drhelius** [comment]
Sorry for that, it should be fixed now.
If you like you can add my email to the pipeline in case it fails.

**Comment by LibretroAdmin** [comment]
Hi,

I'll have to look at how to set it up to email and if that is possible.

In the meantime, the only builds still failing is Android. Here is the pipeline -
https://git.libretro.com/libretro/gearcoleco/-/pipelines/313655

**Comment by drhelius** [comment]
Fixed!

**Comment by LibretroAdmin** [comment]
Yup looks like it passes now, thanks
